# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maininfo.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(13, 13, 781, 521))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter_2)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_day = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_day.setRowCount(10)
        self.tableWidget_day.setColumnCount(3)
        self.tableWidget_day.setObjectName("tableWidget_day")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_day.setItem(1, 0, item)
        self.tableWidget_day.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_day.horizontalHeader().setHighlightSections(True)
        self.tableWidget_day.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_day.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_day.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tableWidget_day, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget_time = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_time.setObjectName("tableWidget_time")
        self.tableWidget_time.setColumnCount(0)
        self.tableWidget_time.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidget_time, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget_subject = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_subject.setObjectName("tableWidget_subject")
        self.tableWidget_subject.setColumnCount(0)
        self.tableWidget_subject.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableWidget_subject, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_room = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_room.setGeometry(QtCore.QRect(10, 10, 753, 328))
        self.tableWidget_room.setObjectName("tableWidget_room")
        self.tableWidget_room.setColumnCount(0)
        self.tableWidget_room.setRowCount(0)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tableWidget_form = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_form.setObjectName("tableWidget_form")
        self.tableWidget_form.setColumnCount(0)
        self.tableWidget_form.setRowCount(0)
        self.gridLayout_7.addWidget(self.tableWidget_form, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.tableWidget_teacher = QtWidgets.QTableWidget(self.tab_13)
        self.tableWidget_teacher.setGeometry(QtCore.QRect(10, 10, 753, 328))
        self.tableWidget_teacher.setObjectName("tableWidget_teacher")
        self.tableWidget_teacher.setColumnCount(0)
        self.tableWidget_teacher.setRowCount(0)
        self.tabWidget.addTab(self.tab_13, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tableWidget_proram = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_proram.setObjectName("tableWidget_proram")
        self.tableWidget_proram.setColumnCount(0)
        self.tableWidget_proram.setRowCount(0)
        self.gridLayout_8.addWidget(self.tableWidget_proram, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.button_edit = QtWidgets.QPushButton(self.splitter)
        self.button_edit.setObjectName("button_edit")
        self.button_add = QtWidgets.QPushButton(self.splitter)
        self.button_add.setObjectName("button_add")
        self.button_delete = QtWidgets.QPushButton(self.splitter)
        self.button_delete.setObjectName("button_delete")
        self.button_next = QtWidgets.QPushButton(self.splitter_2)
        self.button_next.setObjectName("button_next")
        self.progressBar = QtWidgets.QProgressBar(self.splitter_2)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget_day.setSortingEnabled(True)
        __sortingEnabled = self.tableWidget_day.isSortingEnabled()
        self.tableWidget_day.setSortingEnabled(False)
        self.tableWidget_day.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Дни"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Время"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Предметы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Аудитории"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Классы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("MainWindow", "Преподаватель"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Занятия"))
        self.button_edit.setText(_translate("MainWindow", "Редактировать"))
        self.button_add.setText(_translate("MainWindow", "Добавить"))
        self.button_delete.setText(_translate("MainWindow", "Удалить"))
        self.button_next.setText(_translate("MainWindow", "Далее"))

